# Site settings
author: Anna (Raiet) Intraub
title: From 0 to 1
header-img: img/home-bg.png
email: raietsaeed@gmail.com
copyright_name: Anna (Raiet) Intraub
description: > # this means to ignore newlines until "baseurl:"
  Learning to Code
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  raiet13

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
